print(" An ISO: 9001:2015                              Ap govt Regd. No. 205/2018        ")
print("              Authorized by Tally Education PVT. LTD. BENGALURU                   ")
print("==================================================================================")
print("                             SRI GOOD WILL COMPUTERS                 TEPL         ")
print("----------------------------------------------------------------------------------")
print("                     The Institute of Computers and Accounts                      ")
print("----------------------------------------------------------------------------------")
print("               📍2-257-2,society colony,NTR circle,MADANAPALLE-517325            ")
print("                 ☎️08571-224222   |  📞 99599 98374   | 📱88838 98767           ")
print("==================================================================================")
print("                           _______                                                ")
print("Receipt no:               |RECEIPT|                   Date:_________________      ")
print("__________________________________________________________________________________")
print("Name of the student: _____________________________________________________________")
print("course:______________________ Batch no: ___________________ Timing:_______________")
print("SI.No    |           PARTICULARS                |          AMOUNT                 ")
print("__________________________________________________________________________________")
print("                                                                                  ")
print("|         |                                      |    Rs.                |   Ps  |")
print("| 1.      |    Course Fees                       |                       |       |")
print("| 2.      |    Registration Fees                 |                       |       |")
print("| 3.      |    Examination Fees                  |                       |       |")
print("| 4.      |    Tally Prime Exam Fees             |                       |       |")
print("| 5.      |    Books/Others                      |                       |       |")
print("__________________________________________________________________________________")
print("                                                                                  ")
print(" Due Amount: _______________         TOTAL :     _________________________        ")
print("Due to be paid:_____________")
print("Rupees in words: _________________________________________________________        ")
print("Mode of payment:                                                                  ")
print("[ ] Cash ___________  [ ] UPI/ONLINE ____________  [ ] Cheque/DD ______________   ")
print("                                                                                  ")      
print("                                                                                  ")
print("___________________________                            ___________________        ")
print(" student/guardian signature                            Recievers signature        ")
print("                                                             with seal            ")
print("Fee once paid shall not be refunded")
print("                             www.srigoodwill.com                                  ")
print("==================================================================================")


         